### ISSUE TITLE
你好，如何设置悬浮按钮只在app内部使用，退出后台悬浮按钮隐藏，打开app按钮再出现？

### ISSUE THREAD

**Issue by EsZhangHome** [Yuye584312311/IMusic#5]

**Comment by hty527** [comment]
你好，这个需求解决了吗？源码中MusicApplication类下有相关代码，注释了，您这边开启这段代码即可：
        //APP前后台监测,悬浮窗的处理
        AppBackgroundManager.getInstance().setAppStateListener( new AppBackgroundManager.IAppStateChangeListener() {
            @Override
            public void onAppStateChanged(String activityName,boolean isAppForceground) {
                //APP不可见并且直接是从播放器界面不可见的，让悬浮窗显示出来
                if(!isAppForceground&&activityName.equals(MusicPlayerActivity.class.getCanonicalName())){
                    MusicWindowManager.getInstance().onVisible();
                }
//                if(isAppForceground){
//                    MusicWindowManager.getInstance().onVisible();
//                }else{
//                    MusicWindowManager.getInstance().onInvisible();
//                }
            }
        });

**Comment by EsZhangHome** [comment]
谢谢，当时没有看application，已经解决了。
